spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    jdbc-url: jdbc:sqlserver://211.62.79.3:16363;databaseName=WEBDB;encrypt=false;
    username: s_web#
    password: dnpq@qhdks

  second-datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    jdbc-url: jdbc:sqlserver://211.62.79.7:16363;databaseName=WEBDB;encrypt=false;
    username: s_sys#
    password: Tmrl@qhdks

  third-datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://localhost:3306/admin?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: root1234!!



  jpa:
    show-sql: true
    hibernate:
      #ddl-auto: create
      properties:
        hibernate:
          dialect: org.hibernate.dialect.SQLServerDialect
          format_sql: true
          use_sql_comments: true


  sql:
    init:
      platform: mysql

  logging:
    level:
      root: INFO
      com.example.concert.filter.LogFilter: DEBUG

  mybatis:
    mapper-locations: classpath:/mapper/**/*.xml

jwt:
  secret: "vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalaaaaaaaaaaaaaaaabbbbb"